### ISSUE TITLE
Approach to show loading for multiple api calls

### ISSUE THREAD

**Issue by rufatisayev** [rafa19/simple-news-app#1]
How can I show loading if I have multiple api calls in single screen? What approach do you suggest?

**Comment by rafa19** [comment]
One approach would be to create a mutable `LiveData` to update the loading status and, on the view side just show and hide regarding loading status. Here is an example code:

This would be your ViewModel
<img width="763" alt="image" src="https://github.com/rafa19/simple-news-app/assets/7234893/bb27abad-551d-4bb6-9197-bbfac88f7f4c">

And on the view side, you will listen to loading status changes
<img width="740" alt="image" src="https://github.com/rafa19/simple-news-app/assets/7234893/27b594c0-cfdd-46ab-b246-73bdb72231d7">

**Comment by rufatisayev** [comment]
Hi, yes mutable LiveData would be best option. Thank so much. Appreciate it
